// GENERATED by `npm run db:types`. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      admins: {
        Row: {
          created_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admins_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      challenges: {
        Row: {
          created_at: string
          expires_at: string
          from_user: string
          game_type: string
          id: string
          match_id: string | null
          options: Json
          rating_pool: string
          responded_at: string | null
          stake_amount: number
          status: string
          to_user: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string
          from_user: string
          game_type: string
          id?: string
          match_id?: string | null
          options?: Json
          rating_pool?: string
          responded_at?: string | null
          stake_amount: number
          status?: string
          to_user?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string
          from_user?: string
          game_type?: string
          id?: string
          match_id?: string | null
          options?: Json
          rating_pool?: string
          responded_at?: string | null
          stake_amount?: number
          status?: string
          to_user?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "challenges_from_user_fkey"
            columns: ["from_user"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "challenges_game_type_fkey"
            columns: ["game_type"]
            isOneToOne: false
            referencedRelation: "game_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "challenges_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "challenges_to_user_fkey"
            columns: ["to_user"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      chess_games: {
        Row: {
          black_time_ms: number
          draw_offer_by: string | null
          fen: string
          increment_ms: number
          last_move_at: string
          match_id: string
          pgn: string
          ply: number
          turn: string
          white_time_ms: number
        }
        Insert: {
          black_time_ms: number
          draw_offer_by?: string | null
          fen: string
          increment_ms?: number
          last_move_at?: string
          match_id: string
          pgn?: string
          ply?: number
          turn?: string
          white_time_ms: number
        }
        Update: {
          black_time_ms?: number
          draw_offer_by?: string | null
          fen?: string
          increment_ms?: number
          last_move_at?: string
          match_id?: string
          pgn?: string
          ply?: number
          turn?: string
          white_time_ms?: number
        }
        Relationships: [
          {
            foreignKeyName: "chess_games_draw_offer_by_fkey"
            columns: ["draw_offer_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chess_games_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      chess_moves: {
        Row: {
          created_at: string
          fen_after: string
          match_id: string
          ply: number
          san: string
          time_left_ms: number
          uci: string
        }
        Insert: {
          created_at?: string
          fen_after: string
          match_id: string
          ply: number
          san: string
          time_left_ms: number
          uci: string
        }
        Update: {
          created_at?: string
          fen_after?: string
          match_id?: string
          ply?: number
          san?: string
          time_left_ms?: number
          uci?: string
        }
        Relationships: [
          {
            foreignKeyName: "chess_moves_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          country_code: string
          created_at: string
          currency_code: string
          currency_minor_units: number
          default_language: string
          is_active: boolean
          max_deposit: number | null
          max_withdrawal: number | null
          min_deposit: number | null
          min_withdrawal: number | null
          name: string
          payment_providers: string[]
          rate_updated_at: string | null
          real_money_enabled: boolean
          token_to_currency_rate: number | null
          usd_exchange_rate: number | null
        }
        Insert: {
          country_code: string
          created_at?: string
          currency_code: string
          currency_minor_units?: number
          default_language?: string
          is_active?: boolean
          max_deposit?: number | null
          max_withdrawal?: number | null
          min_deposit?: number | null
          min_withdrawal?: number | null
          name: string
          payment_providers?: string[]
          rate_updated_at?: string | null
          real_money_enabled?: boolean
          token_to_currency_rate?: number | null
          usd_exchange_rate?: number | null
        }
        Update: {
          country_code?: string
          created_at?: string
          currency_code?: string
          currency_minor_units?: number
          default_language?: string
          is_active?: boolean
          max_deposit?: number | null
          max_withdrawal?: number | null
          min_deposit?: number | null
          min_withdrawal?: number | null
          name?: string
          payment_providers?: string[]
          rate_updated_at?: string | null
          real_money_enabled?: boolean
          token_to_currency_rate?: number | null
          usd_exchange_rate?: number | null
        }
        Relationships: []
      }
      direct_messages: {
        Row: {
          body: string
          created_at: string
          id: number
          read_at: string | null
          recipient_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: never
          read_at?: string | null
          recipient_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: never
          read_at?: string | null
          recipient_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "direct_messages_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "direct_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      escrow: {
        Row: {
          amount: number
          balance_type: string
          created_at: string
          id: number
          match_id: string
          released_at: string | null
          status: string
          user_id: string
        }
        Insert: {
          amount: number
          balance_type: string
          created_at?: string
          id?: never
          match_id: string
          released_at?: string | null
          status?: string
          user_id: string
        }
        Update: {
          amount?: number
          balance_type?: string
          created_at?: string
          id?: never
          match_id?: string
          released_at?: string | null
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "escrow_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "escrow_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      friendships: {
        Row: {
          addressee_id: string
          created_at: string
          id: string
          requester_id: string
          responded_at: string | null
          status: string
        }
        Insert: {
          addressee_id: string
          created_at?: string
          id?: string
          requester_id: string
          responded_at?: string | null
          status?: string
        }
        Update: {
          addressee_id?: string
          created_at?: string
          id?: string
          requester_id?: string
          responded_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "friendships_addressee_id_fkey"
            columns: ["addressee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      game_types: {
        Row: {
          created_at: string
          id: string
          max_players: number
          min_players: number
          name: string
          options_schema: Json
          rating_pools: string[]
          sort_order: number
          stake_levels: number[]
          status: string
        }
        Insert: {
          created_at?: string
          id: string
          max_players?: number
          min_players?: number
          name: string
          options_schema?: Json
          rating_pools?: string[]
          sort_order?: number
          stake_levels?: number[]
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          max_players?: number
          min_players?: number
          name?: string
          options_schema?: Json
          rating_pools?: string[]
          sort_order?: number
          stake_levels?: number[]
          status?: string
        }
        Relationships: []
      }
      ledger_entries: {
        Row: {
          amount: number
          balance_after: number
          balance_type: string
          created_at: string
          entry_type: string
          id: number
          idempotency_key: string | null
          match_id: string | null
          payment_id: string | null
          tournament_id: string | null
          user_id: string
        }
        Insert: {
          amount: number
          balance_after: number
          balance_type: string
          created_at?: string
          entry_type: string
          id?: never
          idempotency_key?: string | null
          match_id?: string | null
          payment_id?: string | null
          tournament_id?: string | null
          user_id: string
        }
        Update: {
          amount?: number
          balance_after?: number
          balance_type?: string
          created_at?: string
          entry_type?: string
          id?: never
          idempotency_key?: string | null
          match_id?: string | null
          payment_id?: string | null
          tournament_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ledger_entries_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ledger_entries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ludo_games: {
        Row: {
          acted: Json
          capture_home: boolean
          deadline: string | null
          dice: Json
          dice_count: number
          die: number | null
          extra: boolean
          gone: Json
          last_event: Json | null
          match_id: string
          misses: Json
          phase: string
          pieces_each: number
          places: Json
          positions: Json
          rolled: Json
          sixes: number
          teams: Json
          turn: string
          turn_no: number
          turn_seconds: number
          updated_at: string
        }
        Insert: {
          acted?: Json
          capture_home?: boolean
          deadline?: string | null
          dice?: Json
          dice_count?: number
          die?: number | null
          extra?: boolean
          gone?: Json
          last_event?: Json | null
          match_id: string
          misses?: Json
          phase?: string
          pieces_each: number
          places?: Json
          positions: Json
          rolled?: Json
          sixes?: number
          teams?: Json
          turn: string
          turn_no?: number
          turn_seconds: number
          updated_at?: string
        }
        Update: {
          acted?: Json
          capture_home?: boolean
          deadline?: string | null
          dice?: Json
          dice_count?: number
          die?: number | null
          extra?: boolean
          gone?: Json
          last_event?: Json | null
          match_id?: string
          misses?: Json
          phase?: string
          pieces_each?: number
          places?: Json
          positions?: Json
          rolled?: Json
          sixes?: number
          teams?: Json
          turn?: string
          turn_no?: number
          turn_seconds?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ludo_games_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      ludo_moves: {
        Row: {
          auto: boolean
          captured: number
          color: string | null
          created_at: string
          die: number
          from_progress: number | null
          full_count: boolean
          match_id: string
          piece: number | null
          seat: string
          seq: number
          to_progress: number | null
        }
        Insert: {
          auto?: boolean
          captured?: number
          color?: string | null
          created_at?: string
          die: number
          from_progress?: number | null
          full_count?: boolean
          match_id: string
          piece?: number | null
          seat: string
          seq: number
          to_progress?: number | null
        }
        Update: {
          auto?: boolean
          captured?: number
          color?: string | null
          created_at?: string
          die?: number
          from_progress?: number | null
          full_count?: boolean
          match_id?: string
          piece?: number | null
          seat?: string
          seq?: number
          to_progress?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "ludo_moves_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      match_messages: {
        Row: {
          body: string
          created_at: string
          id: number
          kind: string
          match_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: never
          kind: string
          match_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: never
          kind?: string
          match_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_messages_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      match_players: {
        Row: {
          joined_at: string
          match_id: string
          rating_after: number | null
          rating_before: number | null
          seat: string
          seat_order: number | null
          tokens_change: number | null
          user_id: string
        }
        Insert: {
          joined_at?: string
          match_id: string
          rating_after?: number | null
          rating_before?: number | null
          seat: string
          seat_order?: number | null
          tokens_change?: number | null
          user_id: string
        }
        Update: {
          joined_at?: string
          match_id?: string
          rating_after?: number | null
          rating_before?: number | null
          seat?: string
          seat_order?: number | null
          tokens_change?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_players_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_players_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      match_queue: {
        Row: {
          country_code: string | null
          game_type: string
          heartbeat_at: string
          joined_at: string
          options: Json
          prefer_same_country: boolean
          rating: number
          rating_pool: string
          stake_amount: number
          user_id: string
        }
        Insert: {
          country_code?: string | null
          game_type: string
          heartbeat_at?: string
          joined_at?: string
          options?: Json
          prefer_same_country?: boolean
          rating: number
          rating_pool?: string
          stake_amount: number
          user_id: string
        }
        Update: {
          country_code?: string | null
          game_type?: string
          heartbeat_at?: string
          joined_at?: string
          options?: Json
          prefer_same_country?: boolean
          rating?: number
          rating_pool?: string
          stake_amount?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_queue_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["country_code"]
          },
          {
            foreignKeyName: "match_queue_game_type_fkey"
            columns: ["game_type"]
            isOneToOne: false
            referencedRelation: "game_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_queue_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matches: {
        Row: {
          created_at: string
          end_reason: string | null
          finished_at: string | null
          game_type: string
          id: string
          options: Json
          rating_pool: string
          result: string | null
          settled: boolean
          settled_at: string | null
          stake_amount: number
          started_at: string | null
          status: string
          tournament_id: string | null
          tournament_round: number | null
          winner_id: string | null
        }
        Insert: {
          created_at?: string
          end_reason?: string | null
          finished_at?: string | null
          game_type: string
          id?: string
          options?: Json
          rating_pool?: string
          result?: string | null
          settled?: boolean
          settled_at?: string | null
          stake_amount: number
          started_at?: string | null
          status?: string
          tournament_id?: string | null
          tournament_round?: number | null
          winner_id?: string | null
        }
        Update: {
          created_at?: string
          end_reason?: string | null
          finished_at?: string | null
          game_type?: string
          id?: string
          options?: Json
          rating_pool?: string
          result?: string | null
          settled?: boolean
          settled_at?: string | null
          stake_amount?: number
          started_at?: string | null
          status?: string
          tournament_id?: string | null
          tournament_round?: number | null
          winner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "matches_game_type_fkey"
            columns: ["game_type"]
            isOneToOne: false
            referencedRelation: "game_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matches_winner_id_fkey"
            columns: ["winner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          country_code: string
          created_at: string
          currency_amount: number
          currency_code: string
          direction: string
          failure_reason: string | null
          id: string
          idempotency_key: string
          phone_e164: string | null
          provider: string
          provider_reference: string | null
          rate_used: number
          reviewed_by: string | null
          status: string
          token_amount: number
          updated_at: string
          user_id: string
        }
        Insert: {
          country_code: string
          created_at?: string
          currency_amount: number
          currency_code: string
          direction: string
          failure_reason?: string | null
          id?: string
          idempotency_key: string
          phone_e164?: string | null
          provider: string
          provider_reference?: string | null
          rate_used: number
          reviewed_by?: string | null
          status?: string
          token_amount: number
          updated_at?: string
          user_id: string
        }
        Update: {
          country_code?: string
          created_at?: string
          currency_amount?: number
          currency_code?: string
          direction?: string
          failure_reason?: string | null
          id?: string
          idempotency_key?: string
          phone_e164?: string | null
          provider?: string
          provider_reference?: string | null
          rate_used?: number
          reviewed_by?: string | null
          status?: string
          token_amount?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["country_code"]
          },
          {
            foreignKeyName: "payments_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_revenue: {
        Row: {
          amount: number
          cash_amount: number
          created_at: string
          match_id: string
        }
        Insert: {
          amount: number
          cash_amount?: number
          created_at?: string
          match_id: string
        }
        Update: {
          amount?: number
          cash_amount?: number
          created_at?: string
          match_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "platform_revenue_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_settings: {
        Row: {
          bonus_winnings_policy: string
          first_move_abort_seconds: number
          id: boolean
          rake_bps: number
          signup_bonus_amount: number
          token_value_usd: number
          updated_at: string
        }
        Insert: {
          bonus_winnings_policy?: string
          first_move_abort_seconds?: number
          id?: boolean
          rake_bps?: number
          signup_bonus_amount?: number
          token_value_usd?: number
          updated_at?: string
        }
        Update: {
          bonus_winnings_policy?: string
          first_move_abort_seconds?: number
          id?: boolean
          rake_bps?: number
          signup_bonus_amount?: number
          token_value_usd?: number
          updated_at?: string
        }
        Relationships: []
      }
      player_ratings: {
        Row: {
          draws: number
          game_type: string
          games_played: number
          losses: number
          pool: string
          rating: number
          updated_at: string
          user_id: string
          wins: number
        }
        Insert: {
          draws?: number
          game_type: string
          games_played?: number
          losses?: number
          pool?: string
          rating?: number
          updated_at?: string
          user_id: string
          wins?: number
        }
        Update: {
          draws?: number
          game_type?: string
          games_played?: number
          losses?: number
          pool?: string
          rating?: number
          updated_at?: string
          user_id?: string
          wins?: number
        }
        Relationships: [
          {
            foreignKeyName: "player_ratings_game_type_fkey"
            columns: ["game_type"]
            isOneToOne: false
            referencedRelation: "game_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_ratings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pool_games: {
        Row: {
          acted: Json
          ball_in_hand: boolean
          balls: Json
          break_shot: boolean
          deadline: string | null
          fouls: Json
          last_shot: Json | null
          match_id: string
          misses: Json
          phase: string
          shot_no: number
          shot_seconds: number
          solids_seat: string | null
          turn: string
          updated_at: string
          variant: string
        }
        Insert: {
          acted?: Json
          ball_in_hand?: boolean
          balls?: Json
          break_shot?: boolean
          deadline?: string | null
          fouls?: Json
          last_shot?: Json | null
          match_id: string
          misses?: Json
          phase?: string
          shot_no?: number
          shot_seconds: number
          solids_seat?: string | null
          turn?: string
          updated_at?: string
          variant: string
        }
        Update: {
          acted?: Json
          ball_in_hand?: boolean
          balls?: Json
          break_shot?: boolean
          deadline?: string | null
          fouls?: Json
          last_shot?: Json | null
          match_id?: string
          misses?: Json
          phase?: string
          shot_no?: number
          shot_seconds?: number
          solids_seat?: string | null
          turn?: string
          updated_at?: string
          variant?: string
        }
        Relationships: [
          {
            foreignKeyName: "pool_games_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      pool_shots: {
        Row: {
          created_at: string
          match_id: string
          result: Json
          seat: string
          shot: Json | null
          shot_no: number
        }
        Insert: {
          created_at?: string
          match_id: string
          result: Json
          seat: string
          shot?: Json | null
          shot_no: number
        }
        Update: {
          created_at?: string
          match_id?: string
          result?: Json
          seat?: string
          shot?: Json | null
          shot_no?: number
        }
        Relationships: [
          {
            foreignKeyName: "pool_shots_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_private: {
        Row: {
          age_confirmed_at: string | null
          ban_reason: string | null
          is_banned: boolean
          match_chat_enabled: boolean
          phone_e164: string | null
          phone_verified_at: string | null
          preferences: Json
          preferred_language: string
          updated_at: string
          user_id: string
        }
        Insert: {
          age_confirmed_at?: string | null
          ban_reason?: string | null
          is_banned?: boolean
          match_chat_enabled?: boolean
          phone_e164?: string | null
          phone_verified_at?: string | null
          preferences?: Json
          preferred_language?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          age_confirmed_at?: string | null
          ban_reason?: string | null
          is_banned?: boolean
          match_chat_enabled?: boolean
          phone_e164?: string | null
          phone_verified_at?: string | null
          preferences?: Json
          preferred_language?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_private_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          country_code: string | null
          created_at: string
          display_name: string | null
          id: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          country_code?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          country_code?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["country_code"]
          },
        ]
      }
      rematch_offers: {
        Row: {
          created_at: string
          match_id: string
          new_match_id: string | null
          offered_by: string
          responded_at: string | null
          status: string
        }
        Insert: {
          created_at?: string
          match_id: string
          new_match_id?: string | null
          offered_by: string
          responded_at?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          match_id?: string
          new_match_id?: string | null
          offered_by?: string
          responded_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "rematch_offers_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rematch_offers_new_match_id_fkey"
            columns: ["new_match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rematch_offers_offered_by_fkey"
            columns: ["offered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          context: Json
          created_at: string
          id: number
          match_id: string | null
          note: string | null
          reason: string
          reported_id: string
          reporter_id: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
        }
        Insert: {
          context?: Json
          created_at?: string
          id?: never
          match_id?: string | null
          note?: string | null
          reason: string
          reported_id: string
          reporter_id: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
        Update: {
          context?: Json
          created_at?: string
          id?: never
          match_id?: string | null
          note?: string | null
          reason?: string
          reported_id?: string
          reporter_id?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reported_id_fkey"
            columns: ["reported_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_messages: {
        Row: {
          body: string
          created_at: string
          id: number
          sender_id: string
          tournament_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: never
          sender_id: string
          tournament_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: never
          sender_id?: string
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tournament_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_messages_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_pairings: {
        Row: {
          created_at: string
          id: number
          match_id: string | null
          player_a: string
          player_b: string | null
          resolved_at: string | null
          result: string | null
          round: number
          tournament_id: string
        }
        Insert: {
          created_at?: string
          id?: never
          match_id?: string | null
          player_a: string
          player_b?: string | null
          resolved_at?: string | null
          result?: string | null
          round: number
          tournament_id: string
        }
        Update: {
          created_at?: string
          id?: never
          match_id?: string | null
          player_a?: string
          player_b?: string | null
          resolved_at?: string | null
          result?: string | null
          round?: number
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tournament_pairings_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "matches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_pairings_player_a_fkey"
            columns: ["player_a"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_pairings_player_b_fkey"
            columns: ["player_b"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_pairings_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_players: {
        Row: {
          draws: number
          dropped: boolean
          games: number
          had_bye: boolean
          joined_at: string
          last_opponent: string | null
          losses: number
          place: number | null
          points: number
          prize: number
          ready_at: string | null
          seen_at: string | null
          tournament_id: string
          user_id: string
          wins: number
        }
        Insert: {
          draws?: number
          dropped?: boolean
          games?: number
          had_bye?: boolean
          joined_at?: string
          last_opponent?: string | null
          losses?: number
          place?: number | null
          points?: number
          prize?: number
          ready_at?: string | null
          seen_at?: string | null
          tournament_id: string
          user_id: string
          wins?: number
        }
        Update: {
          draws?: number
          dropped?: boolean
          games?: number
          had_bye?: boolean
          joined_at?: string
          last_opponent?: string | null
          losses?: number
          place?: number | null
          points?: number
          prize?: number
          ready_at?: string | null
          seen_at?: string | null
          tournament_id?: string
          user_id?: string
          wins?: number
        }
        Relationships: [
          {
            foreignKeyName: "tournament_players_last_opponent_fkey"
            columns: ["last_opponent"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_players_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_players_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_prizes: {
        Row: {
          amount: number
          balance_type: string
          created_at: string
          id: number
          released_at: string | null
          status: string
          tournament_id: string
          user_id: string
        }
        Insert: {
          amount: number
          balance_type: string
          created_at?: string
          id?: never
          released_at?: string | null
          status?: string
          tournament_id: string
          user_id: string
        }
        Update: {
          amount?: number
          balance_type?: string
          created_at?: string
          id?: never
          released_at?: string | null
          status?: string
          tournament_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tournament_prizes_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournaments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_prizes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tournaments: {
        Row: {
          created_at: string
          created_by: string
          current_round: number
          ends_at: string
          format: string
          game_type: string
          id: string
          name: string
          options: Json
          prize_amount: number
          rating_pool: string
          round_started_at: string | null
          rounds: number | null
          settled: boolean
          settled_at: string | null
          starts_at: string
          status: string
        }
        Insert: {
          created_at?: string
          created_by: string
          current_round?: number
          ends_at: string
          format?: string
          game_type: string
          id?: string
          name: string
          options?: Json
          prize_amount?: number
          rating_pool?: string
          round_started_at?: string | null
          rounds?: number | null
          settled?: boolean
          settled_at?: string | null
          starts_at: string
          status?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          current_round?: number
          ends_at?: string
          format?: string
          game_type?: string
          id?: string
          name?: string
          options?: Json
          prize_amount?: number
          rating_pool?: string
          round_started_at?: string | null
          rounds?: number | null
          settled?: boolean
          settled_at?: string | null
          starts_at?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "tournaments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournaments_game_type_fkey"
            columns: ["game_type"]
            isOneToOne: false
            referencedRelation: "game_types"
            referencedColumns: ["id"]
          },
        ]
      }
      wallets: {
        Row: {
          bonus_balance: number
          cash_balance: number
          updated_at: string
          user_id: string
        }
        Insert: {
          bonus_balance?: number
          cash_balance?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          bonus_balance?: number
          cash_balance?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wallets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_abort_match: {
        Args: { p_admin_id: string; p_match_id: string; p_reason: string }
        Returns: Json
      }
      admin_adjust_balance: {
        Args: {
          p_admin_id: string
          p_amount: number
          p_balance_type: string
          p_reason: string
          p_user_id: string
        }
        Returns: Json
      }
      admin_audit: {
        Args: { p_limit: number; p_offset: number }
        Returns: Json
      }
      admin_integrity: { Args: never; Returns: Json }
      admin_match: { Args: { p_match_id: string }; Returns: Json }
      admin_matches: {
        Args: { p_limit: number; p_offset: number; p_status: string }
        Returns: Json
      }
      admin_overview: { Args: never; Returns: Json }
      admin_player: { Args: { p_user_id: string }; Returns: Json }
      admin_reports: {
        Args: { p_limit: number; p_offset: number; p_status: string }
        Returns: Json
      }
      admin_resolve_report: {
        Args: {
          p_admin_id: string
          p_note: string
          p_report_id: number
          p_status: string
        }
        Returns: Json
      }
      admin_revenue: { Args: { p_days: number }; Returns: Json }
      admin_search_players: {
        Args: { p_limit: number; p_offset: number; p_query: string }
        Returns: Json
      }
      admin_set_ban: {
        Args: {
          p_admin_id: string
          p_banned: boolean
          p_reason: string
          p_user_id: string
        }
        Returns: Json
      }
      assert_ledger_integrity: { Args: never; Returns: undefined }
      block_player: { Args: { p_user_id: string }; Returns: Json }
      challenge_create: {
        Args: {
          p_game_type: string
          p_options: Json
          p_players: number
          p_rating_pool: string
          p_stake: number
          p_to_username: string
          p_user_id: string
        }
        Returns: Json
      }
      challenge_respond: {
        Args: { p_action: string; p_challenge_id: string; p_user_id: string }
        Returns: Json
      }
      chess_apply_move: {
        Args: {
          p_end_reason: string
          p_expected_ply: number
          p_fen_after: string
          p_match_id: string
          p_san: string
          p_uci: string
          p_user_id: string
          p_winner: string
        }
        Returns: Json
      }
      chess_game_action: {
        Args: { p_action: string; p_match_id: string; p_user_id: string }
        Returns: Json
      }
      chess_move_context: {
        Args: { p_match_id: string; p_user_id: string }
        Returns: Json
      }
      is_username_available: { Args: { p_username: string }; Returns: boolean }
      join_match_queue: {
        Args: {
          p_game_type: string
          p_options: Json
          p_players?: number
          p_rating_pool: string
          p_stake: number
          p_user_id: string
        }
        Returns: Json
      }
      landing_stats: {
        Args: never
        Returns: {
          countries_represented: number
          matches_today: number
          players_online: number
        }[]
      }
      leave_match_queue: { Args: { p_user_id: string }; Returns: undefined }
      ludo_action: {
        Args: {
          p_action: string
          p_color?: string
          p_die?: number
          p_full?: boolean
          p_match_id: string
          p_piece: number
          p_turn_no: number
          p_user_id: string
        }
        Returns: Json
      }
      mark_messages_read: { Args: { p_from: string }; Returns: undefined }
      match_chat_status: { Args: { p_match_id: string }; Returns: Json }
      pool_apply_shot: {
        Args: {
          p_match_id: string
          p_result: Json
          p_shot: Json
          p_shot_no: number
          p_state: Json
          p_user_id: string
        }
        Returns: Json
      }
      pool_game_action: {
        Args: { p_action: string; p_match_id: string; p_user_id: string }
        Returns: Json
      }
      rematch: {
        Args: { p_action: string; p_match_id: string; p_user_id: string }
        Returns: Json
      }
      remove_friend: { Args: { p_other_id: string }; Returns: Json }
      report_player: {
        Args: {
          p_match_id: string
          p_note: string
          p_reason: string
          p_user_id: string
        }
        Returns: Json
      }
      respond_friend_request: {
        Args: { p_accept: boolean; p_requester_id: string }
        Returns: Json
      }
      send_direct_message: {
        Args: { p_body: string; p_to: string }
        Returns: Json
      }
      send_friend_request: { Args: { p_username: string }; Returns: Json }
      send_match_message: {
        Args: { p_body: string; p_kind: string; p_match_id: string }
        Returns: Json
      }
      send_tournament_message: {
        Args: { p_body: string; p_tournament_id: string }
        Returns: Json
      }
      server_now: { Args: never; Returns: string }
      set_my_country: { Args: { p_country_code: string }; Returns: undefined }
      tournament_cancel: {
        Args: { p_tournament_id: string; p_user_id: string }
        Returns: Json
      }
      tournament_create: {
        Args: {
          p_format: string
          p_game_type: string
          p_minutes: number
          p_name: string
          p_options: Json
          p_players: number
          p_prize: number
          p_rating_pool: string
          p_rounds: number
          p_starts_at: string
          p_user_id: string
        }
        Returns: Json
      }
      tournament_join: {
        Args: { p_tournament_id: string; p_user_id: string }
        Returns: Json
      }
      tournament_ready: {
        Args: { p_ready: boolean; p_tournament_id: string; p_user_id: string }
        Returns: Json
      }
      unblock_player: { Args: { p_user_id: string }; Returns: Json }
      verify_ledger_integrity: {
        Args: never
        Returns: {
          check_name: string
          detail: string
          user_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
