// Builds one SQL file from every migration, for pasting into the Supabase SQL editor when the
// CLI cannot be used. Usage: npm run db:bundle
//
// The bundle runs in a single transaction (all or nothing), refuses to run twice, and records
// each migration in the same history table the Supabase CLI uses, so `supabase db push` later
// knows these are already applied.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const MIGRATIONS_DIR = join(process.cwd(), 'supabase', 'migrations')
const OUT_DIR = join(process.cwd(), 'supabase', 'bundles')

export function buildBundle(): string {
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => /^\d{14}_.+\.sql$/.test(f))
    .sort()

  const versions = files.map((f) => f.slice(0, 14))
  const parts = [
    '-- GENERATED by scripts/bundleMigrations.ts. Do not edit; edit supabase/migrations instead.',
    'begin;',
    'create schema if not exists supabase_migrations;',
    'create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);',
    `do $$
begin
  if exists (select 1 from supabase_migrations.schema_migrations
              where version in (${versions.map((v) => `'${v}'`).join(', ')})) then
    raise exception 'These migrations (or some of them) were already applied to this database.';
  end if;
end;
$$;`,
  ]

  for (const file of files) {
    const version = file.slice(0, 14)
    const name = file.slice(15, -4)
    parts.push(`\n-- ===== ${file} =====`)
    parts.push(readFileSync(join(MIGRATIONS_DIR, file), 'utf8').trim())
    parts.push(`insert into supabase_migrations.schema_migrations (version, name) values ('${version}', '${name}');`)
  }

  parts.push('\ncommit;', '')
  return parts.join('\n')
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('scripts/bundleMigrations.ts')) {
  mkdirSync(OUT_DIR, { recursive: true })
  const out = join(OUT_DIR, 'apply_all.sql')
  writeFileSync(out, buildBundle())
  console.log(`Wrote ${out}`)
}
