// Regenerates the TypeScript types for the hosted database. Usage: npm run db:types
// Run after every migration so the frontend's queries are checked against the real schema.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { managementFetch } from './lib/managementApi.ts'

const res = await managementFetch('/types/typescript?included_schemas=public')
if (!res.ok) throw new Error(`Type generation failed: ${res.status} ${await res.text()}`)
const { types } = (await res.json()) as { types: string }

const out = join(process.cwd(), 'src', 'core', 'lib', 'database.types.ts')
writeFileSync(out, `// GENERATED by \`npm run db:types\`. Do not edit.\n${types}`)
console.log(`Wrote ${out}`)
